FROM rocker/shiny:4.0.5

# system libraries
# Try to only install system libraries you actually need
# Package Manager is a good resource to help discover system deps
RUN apt-get update && apt-get install -y \
    libcurl4-gnutls-dev \
    libssl-dev \
	libmysqlclient-dev \
	libarmadillo-dev \
	libgeos-dev \
	libudunits2-dev \
	libproj-dev \
	libfontconfig1-dev \
	libnode-dev \
	libjq-dev \
	libgdal-dev
	
	


# install R packages required
# Change the packages list to suit your needs
RUN R -e 'install.packages(c("magrittr","rvest","readxl","dplyr","maps","ggplot2","reshape2","ggiraph","RColorBrewer","leaflet","plotly","geojsonio","shiny","shinyWidgets","shinydashboard","shinythemes","plyr","RMySQL","DBI","DT"),repos="https://packagemanager.rstudio.com/cran/__linux__/focal/2021-04-23")'

EXPOSE 3838
# copy the app directory into the image
ADD Dashboard /srv/shiny-server/

# run app
CMD ["/usr/bin/shiny-server"]